export const memberTableColumns = [
  { field: "image", header: "Image" },
  { field: "facilityName", header: "Facility Name" },
  { field: "category", header: "Category" },
  { field: "email", header: "Email" },
  { field: "phone", header: "Phone" },
  { field: "Action", header: "Action" },
];
export const ContributionTableColumns = [
  { field: "image", header: "Image" },
  { field: "facilityName", header: "Facility Name" },
  { field: "category", header: "Category" },
  { field: "amountPaid", header: "Amount Paid" },
  { field: "dueDate", header: "Due Date" },
  { field: "status", header: "Status" },
  { field: "Action", header: "Action" },
];
export const ApplicationTableColumns = [
  { field: "image", header: "Image" },
  { field: "facilityName", header: "Facility Name" },
  { field: "category", header: "Category" },
  { field: "email", header: "Email" },
  { field: "phone", header: "Phone" },
  { field: "status", header: "Status" },
  { field: "Action", header: "Action" },
];
export const membersDummyData = [
  {
    id: 1,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 2,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 3,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 4,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 5,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 6,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 7,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 8,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 9,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
  {
    id: 10,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
  },
];

export const ContributionDummyData = [
  {
    id: 1,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Pending",
  },
  {
    id: 2,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Paid",
  },
  {
    id: 3,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Pending",
  },
  {
    id: 4,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Paid",
  },
  {
    id: 5,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Paid",
  },
  {
    id: 6,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Paid",
  },
  {
    id: 7,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Pending",
  },
  {
    id: 8,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    amountPaid: "Rwf 60,0000",
    dueDate: "23/05/2024",
    status: "Pending",
  },
];
export const ApplicationDummyData = [
  {
    id: 1,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 2,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 3,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 4,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 5,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 6,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 7,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
  {
    id: 8,
    facilityName: "Amaris Medical Clinic",
    category: "General Clinic",
    email: "angelo.igitego@gmail.com",
    phone: "+250 000 000 000",
    status: "Pending",
  },
];
