const districts = [
  {
    id: 0,
    name: "Select district",
    province: "",
  },
  { id: 1, name: "Nyarugenge", province: "Kigali City" },
  { id: 2, name: "Gasabo", province: "Kigali City" },
  { id: 3, name: "Kicukiro", province: "Kigali City" },
  { id: 4, name: "Burera", province: "Northern" },
  { id: 5, name: "Gakenke", province: "Northern" },
  { id: 6, name: "Gicumbi", province: "Northern" },
  { id: 7, name: "Musanze", province: "Northern" },
  { id: 8, name: "Rulindo", province: "Northern" },
  { id: 9, name: "Gisagara", province: "Southern" },
  { id: 10, name: "Huye", province: "Southern" },
  { id: 11, name: "Kamonyi", province: "Southern" },
  { id: 12, name: "Muhanga", province: "Southern" },
  { id: 13, name: "Nyamagabe", province: "Southern" },
  { id: 14, name: "Nyanza", province: "Southern" },
  { id: 15, name: "Nyaruguru", province: "Southern" },
  { id: 16, name: "Ruhango", province: "Southern" },
  { id: 17, name: "Karongi", province: "Western" },
  { id: 18, name: "Ngororero", province: "Western" },
  { id: 19, name: "Nyabihu", province: "Western" },
  { id: 20, name: "Nyamasheke", province: "Western" },
  { id: 21, name: "Rubavu", province: "Western" },
  { id: 22, name: "Rusizi", province: "Western" },
  { id: 23, name: "Rutsiro", province: "Western" },
  { id: 24, name: "Bugesera", province: "Eastern" },
  { id: 25, name: "Gatsibo", province: "Eastern" },
  { id: 26, name: "Kayonza", province: "Eastern" },
  { id: 27, name: "Kirehe", province: "Eastern" },
  { id: 28, name: "Ngoma", province: "Eastern" },
  { id: 29, name: "Nyagatare", province: "Eastern" },
  { id: 30, name: "Rwamagana", province: "Eastern" },
];
export default districts;
